name: Test LS

on:
  workflow_dispatch:

env:
  ROOTFS_DIR: ubuntu-focal-desktop-arm64  # 假设 rootfs 已经解压好
  CUSTOM_DTS: dts/rk3399-nanopi4-rev00.dts

jobs:
  test-out:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test LS
        run: |
          ls -al
          
        
