name: Build NanoPC-T4 Kernel (I2S1 Enabled)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential bc bison flex libssl-dev make gcc-aarch64-linux-gnu

      - name: Clone kernel source
        run: |
          git clone --depth=1 -b nanopi4-v4.19.y https://github.com/friendlyarm/kernel-rockchip.git

      - name: Copy custom DTS
        run: |
          mkdir -p kernel-rockchip/arch/arm64/boot/dts/rockchip
          cp $GITHUB_WORKSPACE/dts/rk3399-nanopi4-rev00.dts \
             kernel-rockchip/arch/arm64/boot/dts/rockchip/

      - name: Configure and build kernel
        run: |
          cd kernel-rockchip
          make ARCH=arm64 nanopi4_linux_defconfig CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Copy Image and DTB for artifact
        run: |
          cd kernel-rockchip
          cp arch/arm64/boot/Image $GITHUB_WORKSPACE/Image
          cp arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dtb \
             $GITHUB_WORKSPACE/rk3399-nanopi4-rev00.dtb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nanopct4-kernel
          path: |
            $GITHUB_WORKSPACE/Image
            $GITHUB_WORKSPACE/rk3399-nanopi4-rev00.dtb

