name: Build NanoPC-T4 Kernel (I2S1 Enabled) with Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup cache for kernel source
        uses: actions/cache@v3
        with:
          path: |
            kernel-rockchip/.build-cache
            kernel-rockchip/.config
          key: ${{ runner.os }}-nanopi4-kernel-${{ hashFiles('dts/rk3399-nanopi4-rev00.dts') }}
          restore-keys: |
            ${{ runner.os }}-nanopi4-kernel-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential bc bison flex libssl-dev make gcc-aarch64-linux-gnu

      - name: Clone kernel source
        run: |
          if [ ! -d kernel-rockchip ]; then
            git clone --depth=1 -b nanopi4-v4.19.y https://github.com/friendlyarm/kernel-rockchip.git
          fi

      - name: Copy custom DTS
        run: |
          cp dts/rk3399-nanopi4-rev00.dts kernel-rockchip/arch/arm64/boot/dts/rockchip/

      - name: Configure and build kernel
        run: |
          cd kernel-rockchip
          make ARCH=arm64 nanopi4_linux_defconfig CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Copy artifacts
        run: |
          cd kernel-rockchip
          cp arch/arm64/boot/Image ../Image
          cp arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dtb ../rk3399-nanopi4-rev00.dtb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nanopct4-kernel
          path: |
            Image
            rk3399-nanopi4-rev00.dtb

