name: FriendlyCore I2S1

on:
  workflow_dispatch:

env:
  ARCH: arm64
  CROSS_COMPILE: aarch64-linux-gnu-
  KERNEL_DEFCONFIG: nanopi4_linux_defconfig
  OUTPUT_DIR: output

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v2
        with:
          repository: friendlyarm/kernel-rockchip
          ref: nanopi4-v4.19.y
          
      - name: Install cross-compiler
        run: |
          sudo apt install -y device-tree-compiler

          
      - name: Replace DTS with custom file
        run: |
          CUSTOM_DTS="arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev01.dts"
          TARGET_DTS="arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dts"

          if [ -f "$CUSTOM_DTS" ]; then
             echo "Replacing DTS: $CUSTOM_DTS → $TARGET_DTS"
             cp "$CUSTOM_DTS" "$TARGET_DTS"
          else
             echo "Custom DTS not found: $CUSTOM_DTS"
             exit 1
          fi

          echo "DTS replaced, validating..."
          dtc -I dts -O dtb -o /dev/null "$TARGET_DTS" || (echo "DTS syntax error!" && exit 1) 

      - name: Compile kernel and device tree
        run: |
          make ARCH=${{ env.ARCH }} CROSS_COMPILE=${{ env.CROSS_COMPILE }} ${KERNEL_DEFCONFIG}
          make ARCH=${{ env.ARCH }} CROSS_COMPILE=${{ env.CROSS_COMPILE }} Image dtbs -j$(nproc)
          mkdir -p ../${{ env.OUTPUT_DIR }}
          cp arch/arm64/boot/Image ../${{ env.OUTPUT_DIR }}/Image
          cp arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dtb ../${{ env.OUTPUT_DIR }}/rk3399-nanopi4-rev00.dtb

      - name: Build minimal root filesystem with Buildroot
        run: |
          git clone https://github.com/buildroot/buildroot.git
          cd buildroot
          make nanopi4_defconfig
          make -j$(nproc)
          cp output/images/rootfs.tar ${GITHUB_WORKSPACE}/${{ env.OUTPUT_DIR }}/rootfs.tar

      - name: Create eflasher image
        run: |
          cd ${GITHUB_WORKSPACE}/${{ env.OUTPUT_DIR }}
          mkdir -p FriendlyCore
          cp Image FriendlyCore/
          cp rk3399-nanopi4-rev00.dtb FriendlyCore/
          cp rootfs.tar FriendlyCore/
          cd FriendlyCore
          tar czf ../FriendlyCore-i2s1-enable.img.gz .

