# 将上面生成的 workflow 内容复制这里
name: Build RK3399 Kernel + SD Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROOTFS_URL: "https://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/ubuntu-20.04-base-arm64.tar.gz"
      CROSS_COMPILE: "aarch64-linux-gnu-"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget unzip build-essential bc bison flex libncurses-dev libssl-dev device-tree-compiler u-boot-tools gcc-aarch64-linux-gnu

      - name: Clone FriendlyElec kernel
        run: |
          git clone --depth 1 -b nanopi4-v4.19.y https://github.com/friendlyarm/kernel-rockchip.git kernel-rockchip

      - name: Download root filesystem
        run: |
          mkdir -p rootfs
          wget -c $ROOTFS_URL -O rootfs/ubuntu-base-arm64.tar.gz
          tar -xzf rootfs/ubuntu-base-arm64.tar.gz -C rootfs

      - name: Configure kernel
        run: |
          cd kernel-rockchip
          make ARCH=arm64 nanopi4_linux_defconfig

      - name: Compile kernel
        run: |
          cd kernel-rockchip
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE Image dtbs modules

      - name: Generate SD boot image
        run: |
          cd kernel-rockchip
          git clone https://github.com/friendlyarm/sd-fuse_rk3399.git sd-fuse
          mkdir -p sdimg
          cp arch/arm64/boot/Image dtbs/*.dtb sd-fuse/
          cd sd-fuse
          ./mk-boot-img.sh Image *.dtb

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: rk3399-sd-image
          path: |
            kernel-rockchip/sd-fuse/boot.img
            kernel-rockchip/arch/arm64/boot/Image
            kernel-rockchip/arch/arm64/boot/dts/rockchip/*.dtb
