name: Build Ubuntu Focal Image (RK3399)

on:
  workflow_dispatch:

env:
  ROOTFS_TGZ_ID: 1LgmYqwXrX6O8YGxgIN9mS9upcOMnpIT5
  ROOTFS_TGZ_FILE: ubuntu-focal-desktop-arm64-images.tgz
  CUSTOM_DTS: dts/rk3399-nanopi4-rev00.dts
  TOOLCHAIN_PATH: /opt/FriendlyARM/toolchain/11.3-aarch64

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bison flex libssl-dev make python3 bc \
            git fakeroot build-essential ncurses-dev gawk wget tar xz-utils \
            cpio unzip rsync file aria2 libelf-dev device-tree-compiler
          pip install gdown

      - name: Download FriendlyARM prebuilt toolchain
        run: |
          mkdir -p $TOOLCHAIN_PATH
          # 假设 toolchain 已上传到某个可用 URL 或 artifact，可直接 wget
          # 示例:
          # wget -O toolchain-11.3-aarch64.tar.xz <url>
          # tar xf toolchain-11.3-aarch64.tar.xz -C /opt/FriendlyARM
          echo "✅ Toolchain should exist at $TOOLCHAIN_PATH"
          export PATH=$TOOLCHAIN_PATH/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          aarch64-linux-gnu-gcc --version

      - name: Prepare out directories
        run: |
          mkdir -p out
          mkdir -p sd-fuse_rk3399/out
          ls -lh

      - name: Clone sd-fuse_rk3399
        run: git clone https://github.com/friendlyarm/sd-fuse_rk3399.git -b kernel-4.19

      - name: Clone kernel
        run: git clone https://github.com/friendlyarm/kernel-rockchip --depth 1 -b nanopi4-v4.19.y kernel-rk3399

      - name: Copy custom DTS
        run: cp $GITHUB_WORKSPACE/${CUSTOM_DTS} kernel-rk3399/arch/arm64/boot/dts/rockchip/

      - name: Build Kernel
        run: |
          cd sd-fuse_rk3399
          mkdir -p out
          export PATH=$TOOLCHAIN_PATH/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          KERNEL_SRC=$PWD/../kernel-rk3399 ./build-kernel.sh ubuntu-focal-desktop-arm64

      - name: Build Kernel headers
        run: |
          cd sd-fuse_rk3399
          export PATH=$TOOLCHAIN_PATH/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          MK_HEADERS_DEB=1 BUILD_THIRD_PARTY_DRIVER=0 \
          KERNEL_SRC=$PWD/../kernel-rk3399 ./build-kernel.sh ubuntu-focal-desktop-arm64

      - name: Build U-Boot
        run: |
          cd sd-fuse_rk3399
          git clone https://github.com/friendlyarm/uboot-rockchip --depth 1 -b nanopi4-v2017.09 uboot-rockchip
          export PATH=$TOOLCHAIN_PATH/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          UBOOT_SRC=$PWD/uboot-rockchip ./build-uboot.sh ubuntu-focal-desktop-arm64

      - name: Build final SD image
        run: |
          cd sd-fuse_rk3399
          mkdir -p out
          ./mk-sd-image.sh ubuntu-focal-desktop-arm64
          ls -lh out/

      - name: Upload SD image
        uses: actions/upload-artifact@v4
        with:
          name: rk3399-sd-image
          path: sd-fuse_rk3399/out/*.img
