name: Build RK3399 Kernel (I2S1 enabled + cache)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev \
            make gcc g++ git wget curl device-tree-compiler

      - name: Clone kernel source
        run: |
          git clone --depth=1 -b nanopi4-v4.19.y https://github.com/friendlyarm/kernel-rockchip.git

      - name: Restore kernel build cache
        uses: actions/cache@v4
        with:
          path: kernel-rockchip/.build-cache
          key: rk3399-kernel-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            rk3399-kernel-${{ runner.os }}-

      - name: Build kernel Image + dtb
        run: |
          cd kernel-rockchip
          # 让内核构建使用缓存目录
          mkdir -p .build-cache
          make O=.build-cache ARCH=arm64 nanopc-t4_defconfig
          make O=.build-cache ARCH=arm64 -j$(nproc)
          cp .build-cache/arch/arm64/boot/Image arch/arm64/boot/Image
          cp .build-cache/arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dtb \
             arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dtb

      - name: Save kernel build cache
        uses: actions/cache@v4
        with:
          path: kernel-rockchip/.build-cache
          key: rk3399-kernel-${{ runner.os }}-${{ github.sha }}

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rk3399-kernel-i2s1
          path: |
            kernel-rockchip/arch/arm64/boot/Image
            kernel-rockchip/arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dtb

