name: Check FriendlyCore Focal Support

on:
  workflow_dispatch:

jobs:
  check-support:
    runs-on: ubuntu-latest

    steps:
    # Checkout the sd-fuse_rk3399 repository
    - name: Checkout sd-fuse_rk3399 repository
      uses: actions/checkout@v4
      with:
        repository: friendlyarm/sd-fuse_rk3399
        ref: master
        path: sd-fuse_rk3399

    # Verify repository checkout and list supported images
    - name: Verify build.sh and list supported images
      run: |
        echo "Listing sd-fuse_rk3399 directory contents:"
        ls -la sd-fuse_rk3399 || echo "Error: sd-fuse_rk3399 directory not found."
        if [ ! -d sd-fuse_rk3399 ]; then
          echo "Error: sd-fuse_rk3399 directory not found."
          exit 1
        fi
        if [ ! -f sd-fuse_rk3399/build.sh ]; then
          echo "Error: build.sh not found in sd-fuse_rk3399."
          exit 1
        fi
        echo "build.sh found. Extracting supported image names:"
        grep -oE '[a-zA-Z0-9_-]+(-arm64|-64|-20\.04)?' sd-fuse_rk3399/build.sh | sort -u | grep -E 'focal|desktop|buildroot|friendlywrt|debian|android|lubuntu'
        if grep -q "friendlycore-focal-arm64" sd-fuse_rk3399/build.sh; then
          echo "build.sh supports friendlycore-focal-arm64."
        else
          echo "Error: build.sh does not support friendlycore-focal-arm64."
          exit 1
        fi
