name: Check Ubuntu Focal Desktop Support

on:
  workflow_dispatch:

jobs:
  check-support:
    runs-on: ubuntu-latest

    steps:
    # Checkout the sd-fuse_rk3399 repository
    - name: Checkout sd-fuse_rk3399 repository
      uses: actions/checkout@v4
      with:
        repository: friendlyarm/sd-fuse_rk3399
        ref: kernel-4.19
        path: sd-fuse_rk3399

    # Verify repository checkout and list supported images
    - name: Verify mk-sd-image.sh and list supported images
      run: |
        echo "Listing sd-fuse_rk3399 directory contents:"
        ls -la sd-fuse_rk3399 || echo "Error: sd-fuse_rk3399 directory not found."
        if [ ! -d sd-fuse_rk3399 ]; then
          echo "Error: sd-fuse_rk3399 directory not found."
          exit 1
        fi
        if [ ! -f sd-fuse_rk3399/mk-sd-image.sh ]; then
          echo "Error: mk-sd-image.sh not found in sd-fuse_rk3399."
          exit 1
        fi
        echo "mk-sd-image.sh found. Supported image names (from README_cn.md):"
        echo -e "buildroot\nfriendlywrt21-kernel4\nfriendlycore-focal-arm64\ndebian-bullseye-desktop-arm64\ndebian-bullseye-minimal-arm64\nubuntu-focal-desktop-arm64\ndebian-bookworm-core-arm64\nubuntu-noble-core-arm64\nandroid10" | sort -u
        echo "Checking mk-sd-image.sh for ubuntu-focal-desktop-arm64:"
        if grep -q "ubuntu-focal-desktop-arm64" sd-fuse_rk3399/mk-sd-image.sh; then
          echo "mk-sd-image.sh supports ubuntu-focal-desktop-arm64."
        else
          echo "Error: mk-sd-image.sh does not support ubuntu-focal-desktop-arm64."
          exit 1
        fi
