name: NanoPC-T4

on:
  workflow_dispatch:

env:
  ARCH: arm64
  CROSS_COMPILE: aarch64-linux-gnu-
  KERNEL_REPO: https://github.com/friendlyarm/kernel-rockchip
  KERNEL_BRANCH: nanopi4-v4.19.y
  KERNEL_DEFCONFIG: nanopi4_linux_defconfig
  OUTPUT_DIR: output

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Copy custom DTS (if exists)
        run: |
          if [ -f dts/rk3399-nanopi4-rev00.dts ]; then
            ls -l
            echo "Replacing DTS with custom version..."
          else
            echo "Using default DTS from kernel repo."
          fi
