name: TEST NanoPC

on:
  workflow_dispatch:

env:
  ARCH: arm64
  CROSS_COMPILE: aarch64-linux-gnu-
  KERNEL_DEFCONFIG: nanopi4_linux_defconfig
  OUTPUT_DIR: output
  DTS_FILE: arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dts
  LOCALVERSION: "" # 避免 Git 仓库缺失报错
  BOOT_IMG: output/boot.img

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: friendlyarm/kernel-rockchip
          ref: nanopi4-v4.19.y
          path: kernel
          fetch-depth: 0  # 完整 Git 仓库，避免内核 setlocalversion 报错
            
      - name: Setup output directory
        run: mkdir -p ${{ env.OUTPUT_DIR }}

      - name: Copy custom DTS (if exists)
        run: |
          echo "$(pwd)"
          ls -l
          if [ -f dts/rk3399-nanopi4-rev00.dts ]; then
            echo "Replacing DTS with custom version..."
            cp dts/rk3399-nanopi4-rev00.dts kernel/arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dts
          else
            echo "Using default DTS from kernel repo."
          fi
