name: FriendlyElec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
      KERNEL_REPO: https://github.com/friendlyarm/kernel-rockchip.git
      KERNEL_BRANCH: nanopi4-v4.19.y
      KERNEL_DEFCONFIG: nanopi4_linux_defconfig
      OUTPUT_DIR: build_out

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            make bc bison flex libssl-dev \
            git build-essential ccache

      - name: Clone FriendlyElec Kernel
        run: |
          git clone --depth=1 -b $KERNEL_BRANCH $KERNEL_REPO kernel

      - name: Clean Kernel Tree
        run: |
          cd kernel
          git clean -xfd
          git reset --hard

      - name: Configure Kernel
        run: |
          cd kernel
          make O="../${OUTPUT_DIR}" ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE $KERNEL_DEFCONFIG

      - name: Build Kernel
        run: |
          cd kernel
          make -j$(nproc) V=1 \
            O="../${OUTPUT_DIR}" ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE \
            Image dtbs modules

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nanopct4-kernel-friendlyelec
          path: |
            ${{ env.OUTPUT_DIR }}/arch/arm64/boot/Image
            ${{ env.OUTPUT_DIR }}/arch/arm64/boot/dts/rockchip/*.dtb
            ${{ env.OUTPUT_DIR }}/.config
